## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to override the default test script
script:
  - julia -e 'import Pkg; Pkg.clone("https://github.com/PetrKryslUCSD/FinEtools.jl.git"); Pkg.test("FinEtools"; coverage=true);'
after_success:
  # push coverage results to Coveralls
  - julia --inline=no --project --code-coverage=user -e 'import Pkg; cd(Pkg.dir("FinEtools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --inline=no --project --code-coverage=user -e 'import Pkg; cd(Pkg.dir("FinEtools")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
